input DiscoverMoviesFilter {
	language: Translations
	region: RegionCode
	includeAdult: Boolean
	includeVideo: Boolean
	primaryReleaseYear: Int
	primaryReleaseDate: DateRangeInput
	releaseDate: DateRangeInput
	withReleaseType: ReleaseTypeInput
	year: Int
	voteCount: NumberRangeInput
	voteAverage: VoteAverageInput
	withCast: IDListInput
	withCrew: IDListInput
	withPeople: IDListInput
	withCompanies: IDListInput
	withGenres: IDListInput
	withKeywords: KeywordInput
	withRuntime: NumberRangeInput
	withOriginalLanguage: Translations
}
