interface Image {
  "The filename of the image. Used to construct URLs given a base URL and a size."
  file: String
  "Returns a URL for an image with the given dimensions or a generated SVG as either a URL or a base64 encoded data URI."
  custom(size: String svg: Boolean color: Palette base64: Boolean): URL
  "Returns a URL for an image in it's original size or a generated SVG as either a URL or a base64 encoded data URI."
  original(svg: Boolean color: Palette base64: Boolean): URL
  "Returns either a URL to or a base64 encoded data URI of the image."
  svg(size: String color: Palette base64: Boolean): URL
  "A hash of extracted colors from the image."
  colors: ExtractedColors
}
