type Logo implements Image {
  file: String
  custom(size: String svg: Boolean color: Palette base64: Boolean): URL
  original(svg: Boolean color: Palette base64: Boolean): URL
  svg(size: String color: Palette base64: Boolean): URL
  colors: ExtractedColors
  "w45"
  icon: URL
  "w92"
  tiny: URL
  "w154"
  small: URL
  "w185"
  medium: URL
  "w300"
  large: URL
  "w500"
  huge: URL
}
