type Movie {
  id: ID!

  # General Details

  name: String!
  tagline: String
  overview: String!
  country: [Country!]!
  languages: [Language!]!
  status: ReleaseStatus!
  genres: [Genre!]!
  keywords: [Keyword!]!
  releaseDate: DateTime
  runtime: Int
  budget: Int!
  revenue: String!
  adult: Boolean!

  # People & Companies

  cast(limit: Int): [Credit!]!
  crew(limit: Int): [Credit!]!
  productionCompanies: [Company!]!

  # Social

  homepage: URL
  socialMedia: SocialMedia

  # Media

  poster: Poster
  backdrop: Backdrop
  images: [MediaImage!]!
  videos(
    language: Translations
    filter: VideoFilter
    first: Int
    ): [Video!]!

  # Ratings & Reviews

  popularity: Float!
  score: Float!
  votes: Int!
  reviews(
    language: Translations
    limit: Int
    page: PageRange = 1
    ): [Review!]!

  # Related

  collection(language: Translations): Collection
  recommended(
    language: Translations
    page: PageRange = 1
    limit: Int
  ): [Movie!]!
  similar(
    language: Translations
    page: PageRange = 1
    limit: Int
  ): [Movie!]!

  # TODO
  # states
  # alternativeTitles(country)
  # changes(start: ISODate, end: ISODate, page: PageRange = 1)
  # releaseDates
  # lists(language: Translations = English, page: PageRange = 1)
}
