type Poster implements Image {
  file: String
  custom(size: String svg: Boolean color: Palette base64: Boolean): URL
  original(svg: Boolean color: Palette base64: Boolean): URL
  svg(size: String color: Palette base64: Boolean): URL
  colors: ExtractedColors
  "w92"
  thumbnail: URL
  "w154"
  tiny: URL
  "w185"
  small: URL
  "w342"
  medium: URL
  "w500"
  large: URL
  "w780"
  huge: URL
}
