enum Translations {
  UAEArabic
  SaudiArabianArabic
  Bulgarian
  Bangla
  Catalan
  Chamorro
  Czech
  Danish
  German
  Greek
  English
  Esperanto
  Spanish
  MexicanSpanish
  Basque
  Farsi
  Finnish
  CanadianFrench
  French
  Hebrew
  Hindi
  Hungarian
  Indonesian
  Italian
  Japanese
  Georgian
  Kannada
  Korean
  Lithuanian
  Malayalam
  BokmalNorwegian
  Dutch
  Norwegian
  Polish
  BrazilianPortuguese
  Portuguese
  Romanian
  Russian
  Slovak
  Slovenian
  Serbian
  Swedish
  Tamil
  Telugu
  Thai
  Turkish
  Ukrainian
  Vietnamese
  ChineseSimplified
  ChineseTraditional
}
